language: android
android:
  components:
    - tools
    - build-tools-23.0.1
    - android-23
    - platform-tools
    - extra-android-m2repository
	- extra-google-google_play_services

  licenses:
    - android-sdk-license-.+
before_install: 
  - cd android_app
  - chmod +x gradlew
  
script:
  - ./gradlew build